# This is the configuration used to check the rubocop source code.

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 90

StringLiterals:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
