language: ruby
services:
  - postgresql
  - redis-server
rvm:
 - 2.2.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bin/rails db:schema:load RAILS_ENV=test
  - bundle exec rspec spec
