---
version: '2'

services:
  # Our Postgresql service:
  postgres:
    container_name: api5_postgres
    image: postgres:9.6
    environment:
      # LC_ALL: pl_PL.UTF-8
      POSTGRES_PASSWORD: 3x1mpl3
      POSTGRES_DB: example_db

    ports:
      - '5439:5432' # Bind host port 5432 to PostgreSQL port 5432

    volumes:
      - 'postgres:/var/lib/postgresql/data'

  # Our Redis service:
  redis:
    container_name: api5_redis
    image: redis:3.2-alpine
    command: redis-server --requirepass yourpassword
    ports:
      - '6380:6379' # Bind host port 6379 to Redis port 6379

    volumes:
      - 'redis:/var/lib/redis/data'

  # Application: ------------------------------------------------------------------------
  # We'll also use this configuration (&app_base) for the websocket server and sidekiq
  web: &app_base
    container_name: web
    build: .
    volumes:
      - .:/app

    ports:
      - '3003:3003' # Bind host port 3000 to app HTTP port 3000

    links: &app_links
      - postgres:postgres.local
      - redis:redis.local
      - cable:ws.dev

    environment: &app_environment
      # PostgreSQL Development Database:
      DATABASE_URL: postgres://postgres:3x1mpl3@postgres.local:5432/example_db?pool=25&encoding=unicode&schema_search_path=public
      # Redis Database:
      REDIS_URL: redis://:yourpassword@redis.local:6379
      WS_URL:    ws://docker.local:28080

      ACTION_CABLE_FRONTEND_URL:            ws://docker.local:28080
      ACTION_CABLE_ALLOWED_REQUEST_ORIGINS: http:\/\/docker.local*
      # Enable the byebug debugging server - this can be overriden
      # from the command line:
      ENABLE_DEBUG_SERVER: 'true'
      # Run the app in the 'development' environment:
      RACK_ENV:  development
      RAILS_ENV: development

    command: bundle exec rails s -p 3003 -b '0.0.0.0'

  # Application: ------------------------------------------------------------------------
  # websocket server
  cable:
    container_name: cable
    <<: *app_base
    ports:
      - '28080:28080'

    links:
      - redis:redis.local

    command: bundle exec puma -b tcp://0.0.0.0:28080 cable/config.ru

  # Application: ------------------------------------------------------------------------
  # background processing server
  sidekiq:
    container_name: sidekiq
    <<: *app_base
    ports:
      - '3100:3000' # Bind host port 3000 to app HTTP port 3000

    links:
      - redis:redis.local

    volumes:
      - .:/app
    # env_file:
    #   - '.env'

    command: bundle exec sidekiq -C config/sidekiq.yml.erb

volumes:
  redis:
  postgres:
