require 'rails_helper'
require 'api/v1/diagrams_controller'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::DiagramsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Api::V1::Diagram. As you add validations to Api::V1::Diagram, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    # skip("Add a hash of attributes valid for your model")
    { name: 'default' }
  }

  let(:invalid_attributes) {
    # skip("Add a hash of attributes invalid for your model")
    { name: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::DiagramsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all api_v1_diagrams as @api_v1_diagrams" do
      diagram = Api::V1::Diagram.create! valid_attributes
      get :index, params: {}, session: valid_session, format: :json
      expect(assigns(:api_v1_diagrams)).to eq([diagram])
    end
  end
end
