require 'rails_helper'
require 'api/v1/shapes_controller'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::ShapesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Api::V1::Shape. As you add validations to Api::V1::Shape, be sure to
  # adjust the attributes here as well.
  let(:canvas) { FactoryGirl.create(:api_v1_canvas) }
  let(:valid_attributes) {
    {
      canvas_id: canvas.id,
      label: 'label 1',
      shape_type: 'Circle',
      descriptors: '{"radius": 10}',
      pos_x: 10,
      pos_y: 20,
    }
  }

  let(:new_attributes) {
    {
      label: 'label new',
      pos_x: 40,
      pos_y: 40,
    }
  }

  let(:invalid_attributes) {
    {
      canvas_id: canvas.id,
      label: '',
      shape_type: 'Circlexxx',
      descriptors: '{"radius": 10}',
      pos_x: 'abc',
      pos_y: 'abc',
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::ShapesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all api_v1_shapes as @api_v1_shapes" do
      shape = Api::V1::Shape.create! valid_attributes
      get :index, params: { canvas_id: canvas.id }, session: valid_session, format: :json
      expect(assigns(:api_v1_shapes)).to eq([shape])
    end
  end

  describe "GET show" do
    it "assigns the requested api_v1_shape as @api_v1_shape" do
      shape = Api::V1::Shape.create! valid_attributes
      get :show, params: { id: shape.to_param }, session: valid_session, format: :json
      expect(assigns(:api_v1_shape)).to eq(shape)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      render_views

      it "creates a new Api::V1::Shape" do
        expect {
          post :create, params: valid_attributes, session: valid_session, format: :json
        }.to change(Api::V1::Shape, :count).by(1)
      end

      it "assigns a newly created api_v1 as @api_v1" do
        post :create, params: valid_attributes, session: valid_session, format: :json
        expect(assigns(:api_v1_shape)).to be_a(Api::V1::Shape)
        # expect(assigns(:api_v1_shape)).to be_persisted
      end

      it "redirects to the created api_v1_shape" do
        post :create, params: valid_attributes, session: valid_session, format: :json
        expect(response).to have_http_status(:created)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved api_v1_shape as @api_v1_shape" do
        post :create, params: invalid_attributes, session: valid_session, format: :json
        expect(assigns(:api_v1_shape)).to be_a_new(Api::V1::Shape)
      end

      it "re-renders the 'new' template" do
        post :create, params: invalid_attributes, session: valid_session, format: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      render_views

      it "updates the requested api_v1_shape" do
        shape = Api::V1::Shape.create! valid_attributes
        put :update, params: { id: shape.id }.merge(new_attributes),
                     session: valid_session, format: :json

        shape.reload
        expect(shape.label).to eql('label new')
        expect(shape.pos_x).to eql(40)
        expect(shape.pos_y).to eql(40)
      end

      it "assigns the requested api_v1_shape as @api_v1_shape" do
        shape = Api::V1::Shape.create! valid_attributes
        put :update, params: { id: shape.id }.merge(new_attributes),
                     session: valid_session, format: :json

        expect(assigns(:api_v1_shape)).to eq(shape)
      end

      it "redirects to the api_v1_shape" do
        shape = Api::V1::Shape.create! valid_attributes
        put :update, params: { id: shape.id }.merge(new_attributes),
                     session: valid_session, format: :json

        expect(response).to have_http_status(:ok)
      end
    end

    describe "with invalid params" do
      render_views

      it "assigns the api_v1 as @api_v1_shape" do
        shape = Api::V1::Shape.create! valid_attributes
        put :update, params: { id: shape.id }.merge(invalid_attributes),
                     session: valid_session, format: :json

        expect(assigns(:api_v1_shape)).to eq(shape)
      end

      it "re-renders the 'edit' template" do
        shape = Api::V1::Shape.create! valid_attributes
        put :update, params: { id: shape.id }.merge(invalid_attributes),
                     session: valid_session, format: :json

        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested api_v1_shape" do
      shape = Api::V1::Shape.create! valid_attributes
      expect {
        delete :destroy, params: { id: shape.to_param },
                         session: valid_session, format: :json
      }.to change(Api::V1::Shape, :count).by(-1)
    end

    it "redirects to the api_v1_shapes list" do
      shape = Api::V1::Shape.create! valid_attributes
      delete :destroy, params: { id: shape.to_param },
                       session: valid_session, format: :json
      expect(response).to have_http_status(:no_content)
    end
  end

end
