production: &production
  # :url: redis://10.10.3.153:6381
  # :host: 10.10.3.153
  # :port: 6381
  # :timeout: 1
development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
