production: &production
  # :url: redis://10.10.3.153:6381
  # :host: 10.10.3.153
  # :port: 6381
  # :timeout: 1
development: &development
  url: <%= ENV['REDIS_URL'] %>
  timeout: 1
  inline: true
test: *development
